### ISSUE TITLE
로그인 유지

### ISSUE THREAD

**Issue by superdevsong** [ran-3roads/Capstone-SportsMate#30]
그냥 스프링만 쓴다면 로그인 유지를 위해서 세션을 쓰면 편할테지만.. react와 스프링 두개의 서버를 함께 쓰므로 세션으로는 해결이 안될수도있다. 사례도 없기도 하다.. 다른 해결책이 필요함

**Comment by ran-3roads** [comment]
각 서버 별로 토큰 처리해주면 될듯 node는 쿠키로 서버는 response한 데이터를 JWT로 관리해서 처리하면 될것 같음
