### ISSUE TITLE
#3_issue image를 어떻게 DB로 보낼지 정해야함.

### ISSUE THREAD

**Issue by ran-3roads** [ran-3roads/Capstone-SportsMate#53]
1. image file을 mysql에 직접 저장한다.
2. image file을 링크주소로 하여 저장하고 파일을 서버에서 관리한다.

1번 방법은 서버에서 트랜잭션 처리를 할때 다루기 편하지만, file들이 많이 축적될 수로 서버에 무리가 갈 수 도 있음. 그렇게 되면 쿼리 속도가 느려질수 있음.

2번 방법은 백업용량이나, DB도 가벼워지므로 원할하게 이용할 수있는데 파일로 따로 보관하게 될 경우 #30  와 같은 보안처리를 해줘야함.

**Comment by superdevsong** [comment]
보안을 좀 더 신경써야 겠지만 2번이 역할을 확실히 분리할수 있고 효율적이기에 더 좋다고 봄
